### ISSUE TITLE
Add GuzzleHttp\Client as dependency on composer.json

### ISSUE THREAD

**Issue by abdyfranco** [benmajor/ExchangeRatesAPI#2]
When the library is installed through composer and the project does not have GuzzleHttp previously installed, the error "'GuzzleHttp\Client' not found' is thrown.

![Screen Shot 2019-07-03 at 3 54 03 PM](https://user-images.githubusercontent.com/23648083/60627296-d7152880-9daa-11e9-90e5-01d05f37c5ac.png)

**Comment by benmajor** [comment]
Thanks. It looks like there was a problem with the `composer.json` file in the repo. I've updated it now to only include one `require` object, and this should now force Composer to include Guzzle. 

See https://github.com/benmajor/ExchangeRatesAPI/commit/90bafa7f0fd604c0fde215044588bc8a666526a5
