### ISSUE TITLE
Cannot call functions from ExchangeRatesAPI.php

### ISSUE THREAD

**Issue by Etv500** [benmajor/ExchangeRatesAPI#3]
Hi,

I am trying to call some functions (E.g. trying to get the base currency below) from the ones available in ExchangeRatesAPI.php to my Wordpress site but they break my site when I do so. Whe I fetch the whole data body using Worpress function wp_remote_get() I can see the expected outcome but I need to show only one rate at a time and take 2 parameters for the 2 currencies so that's why I am trying to use the ExchangeRatesAPI.php functions. Am I doing something wrong or is there any other issue I should be aware of? Thanks in advance for any answer

```
//https://github.com/benmajor/ExchangeRatesAPI#3-getting-started
require_once 'C:\ExchangeRatesAPI-master\src\ExchangeRatesAPI.php';


$request = wp_remote_get( 'https://api.exchangeratesapi.io/latest?base=USD' );
if( is_wp_error( $request ) ) {
	return false; // Bail early
}
$body = wp_remote_retrieve_body( $request );
$data = json_decode( $body );
//echo "<pre>"; //this is for cleaning the data in visualitation
//print_r($data); //print output

use \BenMajor\ExchangeRatesAPI\ExchangeRatesAPI;
use \BenMajor\ExchangeRatesAPI\Response;
use \BenMajor\ExchangeRatesAPI\Exception;

$lookup = new ExchangeRatesAPI();
$base  = $lookup->getBaseCurrency();

function mytest(){
$base=getBaseCurrency();
return $base;}
add_shortcode( 'base', 'mytest' );
```

**Comment by ElvisVlcek** [comment]
Nevermind I fixed it :)

**Comment by benmajor** [comment]
Inside of your `mytest()` function, `getBaseCurrency` is not defined. You should update your code as follows:

```
use \BenMajor\ExchangeRatesAPI\ExchangeRatesAPI;
use \BenMajor\ExchangeRatesAPI\Response;
use \BenMajor\ExchangeRatesAPI\Exception;

function mytest()
{
  $lookup = new ExchangeRatesAPI();
  return $lookup->getBaseCurrency();
}

add_shortcode('base', 'mytest');
```
