### ISSUE TITLE
PHP is not supported

### ISSUE THREAD

**Issue by FA-tinhnd** [benmajor/ExchangeRatesAPI#5]
I noticed in the list
`private $_currencies = [
        'USD', 'GBP', 'EUR', 'JPY', 'BGN', 'CZK', 'DKK', 'HUF', 'PLN', 'RON',
        'SEK', 'CHF', 'ISK', 'NOK', 'HRK', 'RUB', 'TRY', 'AUD', 'BRL', 'CAD',
        'CNY', 'HKD', 'IDR', 'ILS', 'INR', 'KRW', 'MXN', 'MYR', 'NZD', 'BHP',
        'SGD', 'THB', 'ZAR'
    ];`

There are BHP currencies but no PHP
So is there a mistake here?

**Comment by benmajor** [comment]
Thanks, yes this is indeed a bug and the array should contain `PHP` in place of `BHP`. I've just pushed a new release that fixes this (https://github.com/benmajor/ExchangeRatesAPI/commit/591c32bddd8595924b6cd10f18426bc7ec930a2b).

Thanks for spotting!
